meta_product_name: "Bentomo"
meta_title: "Bentomo - warmhearted bento"
meta_description: "Bentomo is a platform that brings delicious home-cooked meals to your favorite convenience store. With taste and health in mind as a focus, every meal is created with care to ensure that every meal is as fresh as can be. Single orders and subscription plans are available that cater to your tastebuds’ needs."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
twitter_account: "@bentomo.official"   # required for Twitter Cards
